services:
    _defaults:
        autowire: true
        autoconfigure: true


    MattDunbar\ShopifyAppBundle\:
        resource: '../../'

    MattDunbar\ShopifyAppBundle\Controller\InstallController:
        arguments:
            - '@MattDunbar\ShopifyAppBundle\EntityFactory\InstallFactory'
            - '@MattDunbar\ShopifyAppBundle\Service\ShopifyApi'
            - '@form.factory'
            - '@twig'
        tags: [ 'controller.service_arguments' ]
        calls:
            -   method: setContainer
                arguments: [ '@Psr\Container\ContainerInterface' ]

    MattDunbar\ShopifyAppBundle\Service\ShopifyApi:
        arguments:
            $appUrlKey: '%env(SHOPIFY_APP_URL_KEY)%'
            $apiKey: '%env(SHOPIFY_API_KEY)%'
            $apiSecret: '%env(SHOPIFY_API_SECRET)%'
            $scopes: '%env(SHOPIFY_SCOPES)%'
            $hostName: '%env(SHOPIFY_HOST_NAME)%'
