services:
    MattDunbar\ShopifyAppBundle\Service\ShopifyApi:
        arguments:
            $appUrlKey: '%env(SHOPIFY_APP_URL_KEY)%'
            $apiKey: '%env(SHOPIFY_API_KEY)%'
            $apiSecret: '%env(SHOPIFY_API_SECRET)%'
            $scopes: '%env(SHOPIFY_SCOPES)%'
            $hostName: '%env(SHOPIFY_HOST_NAME)%'
