name: Run Tests
on: [ push ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    extensions: :psr
            -   uses: actions/checkout@v3
            -   uses: php-actions/composer@v6
                with:
                    php_version: 8.2
            -   run: php vendor/bin/grumphp run